#!/usr/bin/env bash
# A script that will display information about subdomains, after configuring your domain zone so
# that the subdomain www points to your load-balancer IP (lb-01), and adding other subdomains.

function get_record() {
    domain=$1
    subdomain=$2
	record_type=$3
    destination=$(dig +short $subdomain.$domain $record_type)
	if [ -z "$destination" ]; then
        echo "No $record_type record found for $subdomain.$domain"
    else
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    fi
}

function audit_subdomain() {
    domain=$1
    subdomain=$2
    record_type=$(dig +short $subdomain.$domain | awk '{ print $4 }')
    destination=$(get_record $domain $subdomain)

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

function audit_domain() {
    domain=$1
    audit_subdomain $domain www
    audit_subdomain $domain lb-01
    audit_subdomain $domain web-01
    audit_subdomain $domain web-02
}

if [[ $# -eq 1 ]]; then
    audit_domain $1
elif [[ $# -eq 2 ]]; then
    audit_subdomain $1 $2
else
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
fi 