#!/usr/bin/env bash
# A script that will display information about subdomains, after configuring your domain zone so
# that the subdomain www points to your load-balancer IP (lb-01), and adding other subdomains.

function get_record() {
    local domain=$1
    local subdomain=$2
    dig +short $subdomain.$domain | awk '{ print $1 }'
}

function audit_subdomain() {
    local domain=$1
    local subdomain=$2
    local record_type=$(dig +short $subdomain.$domain | awk '{ print $4 }')
    local destination=$(get_record $domain $subdomain)

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

function audit_domain() {
    local domain=$1
    audit_subdomain $domain www
    audit_subdomain $domain lb-01
    audit_subdomain $domain web-01
    audit_subdomain $domain web-02
}

if [[ $# -eq 1 ]]; then
    audit_domain $1
elif [[ $# -eq 2 ]]; then
    audit_subdomain $1 $2
else
    echo "Usage: $0 <domain> [<subdomain>]"
fi
