#!/usr/bin/env bash
# A script that configures a new Ubuntu machine.

sudo apt update
sudo apt install -y haproxy

sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
sudo touch /etc/haproxy/haproxy.cfg

# Add the following content to the configuration file
sudo bash -c 'cat <<EOF > /etc/haproxy/haproxy.cfg
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server 134627-web-01 100.26.177.16:80 check
	server 134627-web-02 100.26.9.154 check
EOF'

# Verify the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Start HAproxy service and enable it to start automatically on boot
sudo systemctl start haproxy
sudo systemctl enable haproxy