#!/usr/bin/env bash
#!/bin/bash

# Get the current date in the format of day-month-year
DATE=$(date +"%d-%m-%Y")

# Create a MySQL dump of all databases
mysqldump --all-databases > backup.sql

# Create a compressed archive of the MySQL dump
tar -czvf ${DATE}.tar.gz backup.sql

echo "MySQL backup completed: ${DATE}.tar.gz"
