#!/usr/bin/env bash
# A script that listens on port 80 to find out what’s keeping your Ubuntu container’s Nginx installation

sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
systemctl reload nginx
