#!/bin/env bash
# listens on port 80
if service nginx status | grep -q "Active: active (running)"; then
  echo "Nginx is already running."
else
  service nginx stop
  killall nginx

  sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
  service nginx start